logging:
    level:
        org.springframework.data.r2dbc: DEBUG

spring:
    flyway:
        baseline-on-migrate: true
        url: jdbc:postgresql://localhost:5432/groceries
        user: postgres
        password: test
        locations: classpath:db/migration
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/groceries
        username: postgres
        password: test
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
            platform: postgres