logging:
    level:
        root: INFO
        org.springframework.data.r2dbc: INFO
        reactor: INFO
        com.hedley.groceriesstats: INFO

spring:
    main:
        web-application-type: reactive
    flyway:
        baseline-on-migrate: true
        url: jdbc:postgresql://localhost:5432/groceries
        user: postgres
        password: test
        locations: classpath:db/migration
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/groceries
        username: postgres
        password: test
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            show-sql: true
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
            platform: postgres
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true